server:
  port: 8010
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: zuul-server
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka,http://localhost:8005/eureka
  instance:
    prefer-ip-address: true

